# Configuration file for MegaLinter
# See all available variables at https://oxsecurity.github.io/megalinter/configuration/ and in linters documentation
PRINT_ALPACA: false
SHOW_ELAPSED_TIME: false
FILEIO_REPORTER: false
FLAVOR: terraform
BASH_SHELLCHECK_ARGUMENTS: "-e SC2021 -e SC2002"
EMAIL_REPORTER_EMAIL: "charlie.smith@opencastsoftware.com"
ENABLE_LINTERS:
  - BASH_SHELLCHECK
  - REPOSITORY_GITLEAKS
  - JSON_PRETTIER
  - YAML_PRETTIER
  # - REPOSITORY_TRIVY

  # - CSS_STYLELINT
  # - HTML_HTMLHINT
  # - JSON_PRETTIER
  # - SPELL
  # - TERRAFORM_TFLINT
  # - TERRAFORM_TERRASCAN
  # - TERRAFORM_CHECKOV
  # - TERRAFORM_TERRAFORM_FMT
